# Generated by Django 4.0 on 2022-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_videos_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
