# Generated by Django 4.0 on 2022-01-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0004_alter_videos_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='compressed',
            field=models.BooleanField(default=False),
        ),
    ]
